name: publish to crates.io
on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  publish:
    defaults:
      run:
        working-directory: ./autoget

    env:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      CARGO_TERM_COLOR: always

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - name: dry run release
        run: cargo publish --dry-run --token $CRATES_IO_TOKEN

      - name: release
        run: cargo publish --token $CRATES_IO_TOKEN
